spring.application.name=AIJob-Portal
spring.datasource.url=jdbc:mysql://localhost:3306/aijobportal
spring.datasource.username=root
spring.datasource.password=sujatha@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true